numo-linalg.gemspec

This change is needed to use with the latest numo-narray (0.9.1.0).

Allow to use with numo-narray-0.9.1.0

---

lib/numo/linalg/autoloader.rb

The purpose of this Pull Request is adding a module that searches and loads backend libraries automatically. The appropriate backend libraries for an execution environment are loaded by writing the following require statement:
`require 'numo/linalg/autoloader'`
I confirmed that the module works on macOS, Ubuntu, and CentOS. I have already published the module as the ruby gem ( https://rubygems.org/gems/numo-linalg-autoloader ) but I will be happy if the module is included in the Numo::Linalg.

Add a module searching and loading backend libraries automatically

---

lib/numo/linalg/function.rb

This pull request fixes the bugs about the `_make_complex_eigvecs` method.
To make class methods in Module private, it should to use the `private_class_method` method.
In addition, the `|` operator has higher precedence than the `>` operator.
I found the bugs when I gave a matrix of Numo::DFloat to the Numo::Linalg::eig method.
```ruby
x = Numo::DFloat.new(3, 3).rand
Numo::Linalg::eig(x)
```

Fix NoMethodError and TypeError about _make_complex_eigvecs method

---

ext/numo/linalg/lapack/gen/spec.rb
ext/numo/linalg/lapack/lapack.c
ext/numo/linalg/lapack/numo_lapack.h
ext/numo/linalg/lapack/tmpl/sygvx.c
lib/numo/linalg/function.rb

I would like to add new option named `vals_range` to the `eigh` and `eigvalsh` method. The vals_range option specifies the range of indices of the eigenvalues (and corresponding eigenvectors) to be calculated.
Most machine learning algorithms including calculation of eigenvalue problem such as Principal Component Analysis do not require all eigenvalues and eigenvectors. If it is possible to specify the range of eigenvalues required in the eigh method, execution of these algorithms is speeded up.
The `sygvx` function in LAPACK can select the indices of eigenvalues and eigenvectors to be calculated. I added new template for sygvx function, and then fixed the codes of the eigh and eigvalsh method to call sygvx function.
When calculating 10 small eigenvalues and corresponding eigenvectors of …

Add new option specifying the range of eigenvalues to the eigh and eigvalsh methods

---

ext/numo/linalg/blas/tmpl/mv.c

I found a bug on the `Numo::Linalg.dot` method. The bug occurs when performing vector-matrix product:
```ruby
> require ‘numo/linalg/autoloader’
=> true
> a=Numo::DFloat.new(3,5).rand
=> Numo::DFloat#shape=[3,5]
[[0.0617545, 0.373067, 0.794815, 0.201042, 0.116041],
[0.344032, 0.539948, 0.737815, 0.165089, 0.0508827],
[0.108065, 0.0687079, 0.904121, 0.478644, 0.342969]]
> b=Numo::DFloat.new(3).rand
=> Numo::DFloat#shape=[3]
[0.164541, 0.74603, 0.138994]
> b.dot(a)
=> Numo::DFloat#shape=[5]
[0.28184, 0.473752, 0.80688, 0, 0]
```
My environment running the above codes is as follows:
```bash
$ ruby -v
ruby 2.2.9p480 (2017-12-15 revision 61259) [x86_64-darwin17]
$ gem list | grep numo
numo-linalg (0.1.2)
numo-narray (0.9.1.2)
```
And I used `Intel MKL` and `OpenBLAS` for the background …

Fix bug on the dot method that occurs when performing vector-matrix product

---

lib/numo/linalg/function.rb

I found that performing the dot method with DFloat and DComplex fails on Numo::Linalg.
```ruby
> require 'numo/narray'
=> true
> a=Numo::DFloat.new(2,2).rand
=> Numo::DFloat#shape=[2,2]
[[0.0617545, 0.373067],
[0.794815, 0.201042]]
> b=Numo::DComplex.new(2,2).rand
=> Numo::DComplex#shape=[2,2]
[[0.165089+0.0508827i, 0.108065+0.0687079i],
[0.904121+0.478644i, 0.342969+0.164541i]]
> a.dot(b)
=> Numo::DComplex#shape=[2,2]
[[0.0687551+0.0402282i, 0.0736595+0.071196i],
[0.125421+0.283672i, 0.450884+0.60024i]]
> require ‘numo/linalg/autoloader’
=> true
> a.dot(b)
TypeError: invalid data type for BLAS/LAPACK
…
```
I thought that the cause of this failure lies in the reference processing of UPCAST in the blas_char method. [The specification about …

Fix the UPCAST reference processing in the blas_char method

---

ext/numo/linalg/lapack/tmpl/gqr.c

There is a `printf` function for debugging in the `gqr` template called in `Numo::Linalg.qr`.
```ruby
> Numo::Linalg.qr(Numo::DFloat.new(4, 2).rand)
order=101 m=4 n=4 k=2 lda=4
=> [Numo::DFloat#shape=[4,4]
[[-0.0636761, 0.505476, -0.365994, -0.778773],
[-0.819548, -0.49264, 0.0679184, -0.284665],
[-0.119652, 0.406772, 0.893776, -0.146235],
[-0.55675, 0.579945, -0.250201, 0.53953]], Numo::DFloat#shape=[4,2]
[[-0.969822, -0.640462],
[0, 0.65737],
[0, 0],
[0, 0]]]
> Numo::Linalg::Lapack.call(:orgqr, Numo::DFloat.new(4, 4).rand, Numo::DFloat.new(4, 4).rand)
order=101 m=4 n=4 k=4 lda=4
order=101 m=4 n=4 k=4 lda=4
order=101 m=4 n=4 k=4 lda=4
order=101 m=4 n=4 k=4 lda=4
```
I commented out this printf to suppress the debug message.
```ruby
> Numo::Linalg.qr(Numo::DFloat.new(4, 2).rand)
=> …
```

Suppress debug message on QR decomposition method

---

lib/numo/linalg/function.rb

I found a bug on the `Numo::Linalg.dot` method. The bug occurs when performing dot product with complex vectors.
```ruby
> require 'numo/narray'
=> true
> x=Numo::DComplex.new(3).rand
=> Numo::DComplex#shape=[3]
[0.0617545+0.373067i, 0.794815+0.201042i, 0.116041+0.344032i]
> y=Numo::DComplex.new(3).rand
=> Numo::DComplex#shape=[3]
[0.539948+0.737815i, 0.165089+0.0508827i, 0.108065+0.0687079i]
> x.dot(y)
=> (-0.13202269608393907+0.365782771213446i)
>
*
> require 'numo/linalg/autoloader'
=> true
> x.dot(y)
NoMethodError: undefined method `zdot' for Numo::Linalg::Blas:Module
…
```
The BLAS function that performs dot product of complex vectors are `zdotu` and `cdotu`. Thus, I fixed those functions to be called when given a complex vector to the dot method.
```ruby
> require …
```

Fix bug in the dot method caused by dot product with complex vectors

---

lib/numo/linalg/function.rb
spec/linalg/function/solve_spec.rb

I found a bug in the `solve` method. The solve method raises `NoMethodError` when given a driver option other than `'gen'` such as `'sym'`, `'her'`, and `'pos'`.
```ruby
> require 'numo/linalg/autoloader'
> a = Numo::DFloat.new(3, 3).rand
> b = Numo::DFloat.new(3).rand
> a = 0.5 * (a + a.transpose)
=> Numo::DFloat#shape=[3,3]
[[0.0617545, 0.287054, 0.667382],
[0.287054, 0.116041, 0.540924],
[0.667382, 0.540924, 0.165089]]
> Numo::Linalg.solve(a, b, driver: 'sym')
NoMethodError: undefined method `dsymsv' for Numo::Linalg::Lapack:Module
...
```
This bug occurs because of an inccorect range of the number of characters to cut out from the driver option. In fact, the solve method tries to call the [sysv](https://software.intel.com/en-us/mkl-developer-reference-c-sysv) functions in LAPACK. I …

Fix bug in the solve method when given a driver option other than gen

---

README.md
lib/numo/linalg/function.rb
spec/linalg/function/lu_spec.rb

I would like to add new method for LU decomposition like  [scipy.linalg.lu](https://docs.scipy.org/doc/scipy-1.1.0/reference/generated/scipy.linalg.lu.html). The already existing `lu_fact` method returns the factor and permutation matrices in a form different from the form of LU decomposition. In contrast, the `lu` method in this PR returns three matrices according to the form of LU decomposition that is A = P * L * U:
```ruby
> a = Numo::DFloat.new(4, 3).rand
=> Numo::DFloat#shape=[4,3]
[[0.0617545, 0.373067, 0.794815],
[0.201042, 0.116041, 0.344032],
[0.539948, 0.737815, 0.165089],
[0.0508827, 0.108065, 0.0687079]]
> p, l, u = Numo::Linalg.lu(a)
=> [Numo::DFloat#shape=[4,4]
[[0, 1, 0, 0],
[0, 0, 1, 0],
[1, 0, 0, 0],
[0, 0, 0, 1]], Numo::DFloat(view)#shape=[4,3]
[[1, 0, 0],
[0.114371, 1, …
```

[Propose] Add new method for LU decomposition

---

README.md
lib/numo/linalg/function.rb
spec/linalg/function/cholesky_spec.rb

I would like to add new method for Cholesky factorization like [scipy.linalg.cholesky](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.cholesky.html#scipy.linalg.cholesky). 
[Cholesky factorization](http://mathworld.wolfram.com/CholeskyDecomposition.html) decomposes a symmetric/Hermitian positive define matrix into the product of an upper / lower triangular matrix such as A = U^T * U. The already existing `cho_fact` method returns the matrix which has the Cholesky factor in upper / lower triangular part. However, the remain part consists of random values. Thus, it is difficult to reconstruct the original matrix using the returned matrix from the cho_fact method.
```ruby
> a = Numo::DFloat.new(3,3).rand
> a = a.dot(a.transpose)
=> Numo::DFloat#shape=[3,3]
[[1.22905, …
```

[Propose] Add new method for Cholesky factorization

---

lib/numo/linalg/function.rb

I found a typo in the description about the mode option of qr method. It seems that is not `economy`, but `economic`.

[DOC] Fix description about the mode option of qr method.

---

README.md
lib/numo/linalg/function.rb
spec/linalg/function/ldl_spec.rb

I would like to add new method for LDLt or Bunch-Kaufman factorization like [scipy.linalg.ldl](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.ldl.html) method. Bunch-Kaufman factorization decomposes a symmetric/Hermitian matrix into the product of an upper / lower triangular matrix and block diagonal matrix such as A = U * D * U^T. 
```ruby
> a=Numo::DFloat.new(3,3).rand
> a=0.5*(a+a.transpose)
=> Numo::DFloat#shape=[3,3]
[[0.0617545, 0.287054, 0.667382],
[0.287054, 0.116041, 0.540924],
[0.667382, 0.540924, 0.165089]]
> u,d,p=Numo::Linalg.ldl(a)
> u.dot(d.dot(u.transpose))
=> Numo::DFloat#shape=[3,3]
[[0.0617545, 0.287054, 0.667382],
[0.287054, 0.116041, 0.540924],
[0.667382, 0.540924, 0.165089]]
> u[p,true]
=> Numo::DFloat(view)#shape=[3,3]
[[1, 0.720613, 0.36344],
[0, …
```

[Propose] Add new method for Bunch-Kaufman factorization

---

README.md
lib/numo/linalg/function.rb
spec/linalg/function/null_space_spec.rb
spec/linalg/function/orth_spec.rb

I would like to add new methods for finding an orthogonal basis like [scipy.linalg.orth](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.orth.html#scipy.linalg.orth) and [scipy.linalg.null_space](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.null_space.html#scipy.linalg.null_space) methods.
```ruby
> a = Numo::DFloat[[2, 0, 0], [0, 5, 0]]
=> Numo::DFloat#shape=[2,3]
[[2, 0, 0],
[0, 5, 0]]
> Numo::Linalg.orth(a)
=> Numo::DFloat(view)#shape=[2,2]
[[0, 1],
[1, 0]]
> Numo::Linalg.orth(a.transpose)
=> Numo::DFloat(view)#shape=[3,2]
[[0, 1],
[1, 0],
[0, 0]]
```
```ruby
> b = Numo::DFloat.new(3, 5).rand
> z = Numo::Linalg.null_space(b)
> z.shape
=> [5, 2]
> b.dot(z)
=> Numo::DFloat#shape=[3,2]
[[1.92144e-17, -1.90014e-17],
[6.35517e-17, -2.31759e-17], …
```

[Propose] Add methods for finding an orthogonal basis

---

lib/numo/linalg/function.rb

I wrote patch for improve the performance of the a.dot(b.transpose).
(See https://github.com/ruby-numo/numo-narray/issues/95 for details.)
This patch requires https://github.com/ruby-numo/numo-narray/pull/116 .
```
$ numo_linalg_fp32.yaml
contexts:
- gems: { numo-linalg: 0.1.3 }
require: false
prelude: |
require 'numo/linalg'
- gems: { numo-linalg: 0.2.0 }
require: false
prelude: |
require 'numo/linalg'
loop_count: 1000
prelude: |
X = 1000
Y = 784
YY = Y + 1
a = Numo::SFloat.new(X, Y).seq(0)
b = Numo::SFloat.new(X, Y).seq(0).transpose
c = b.dup
d = Numo::SFloat.new(X, YY).seq(0)[true,1..-1]           # contiguous? => false, transpose? => false
e = Numo::SFloat.new(X, YY).seq(0)[true,1..-1].transpose # contiguous? => false, transpose? => false
f = e.dup
sleep 30
benchmark: …
```

Added contiguous check and fortran_contiguous check to dot method.

---

.travis.yml

Recently, the pull request using the latest develop version of Numo::NArray has been merged. The build test of Numo::Linalg fails because it uses the latest release version Numo::NArray. Therefore, I modified Travis CI config file to use the develop version of Numo::NArray.

Fix Travis CI config file to use the latest develop version of Numo::NArray

---

.travis.yml

Currently, Travis CI uses Ubuntu Xenial as the default Linux distribution. In addition, support of the Ruby 2.3 series has ended. I would like to modify the Travis CI configuration file for these situations.

[Conf] Fix Linux distribution of Travis CI build environment

---

lib/numo/linalg/autoloader.rb

I would like to add the OpenBLAS default installation directory and multi-arch library directory of Debian family to the autoloader search path. In particular, the addition of the multi-arch directory is necessary to support recent versions of Debian / Ubuntu Linux.
The execution example in the environment where  OpenBLAS is built and installed from source and LAPACKE is installed from package manager is as follows:
```sh
$ cat /etc/debian_version
buster/sid
$ irb
irb(main):001:0> require 'numo/linalg/autoloader'
=> true
irb(main):002:0> Numo::Linalg::Autoloader.libs
=> ["/opt/OpenBLAS/lib/libopenblas.so", "/usr/lib/x86_64-linux-gnu/liblapacke.so"]
irb(main):003:0> Numo::Linalg.eigh(Numo::DFloat.new(2, 4).rand.cov)
=> [Numo::DFloat#shape=[2]
[0.0520039, 0.120047], Numo::DFloat#shape=[2, …
```

Add some directories to autoloader search path

---

lib/numo/linalg/function.rb
spec/linalg/function/expm_spec.rb

I have implemented the matrix exponential method for issue https://github.com/ruby-numo/numo-linalg/issues/32 . In scipy, it is implemented using the newer algorithm, but I implemented it using the basic pade approximation method[1].
Example of execution results like [scipy.linalg.expm](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.linalg.expm.html)
```ruby
> Numo::Linalg.expm(Numo::DFloat.zeros([2,2]))
=> Numo::DFloat#shape=[2,2]
[[1, 0],
[0, 1]]
> Numo::Linalg.expm(Numo::DFloat[[1, 2], [-1, 3]] * Complex::I)
=> Numo::DComplex#shape=[2,2]
[[0.426459+1.89218i, -2.13721-0.978113i],
[1.06861+0.489056i, -1.71076+0.914063i]]
```
[1] Gene H. Golub and Charles F. Van Loan, "Matrix Computations 4th Edition: Algorithm 9.3.1," JHU Press, 2013.

Add new method for matrix exponential

---

.travis.yml
lib/numo/linalg/function.rb

Ruby 2.7 changes keyword argument assignment spec. In Numo::Linalg, the Blas.call and Lapack.call methods are affected by this change, so using Numo::Linalg will always occur a deprecation warning.
```sh
lib/numo/linalg/function.rb:20: warning: 
Using the last argument as keyword parameters is deprecated
```
This pull request addresses this issue.

Support for keyword argument of Ruby 2.7

---

.github/workflows/build.yml
Rakefile
ext/numo/linalg/blas/depend.erb
ext/numo/linalg/blas/extconf.rb
ext/numo/linalg/lapack/depend.erb
ext/numo/linalg/lapack/extconf.rb
ext/numo/linalg/mkmf_linalg.rb
numo-linalg.gemspec

I would like to add rake-compiler gem to make the build easy like Numo::NArray. By merging this pull request, native extensions can be built with rake command:
```
$ bundle exec rake compile
mkdir -p tmp/x86_64-darwin20/numo/linalg/blas/3.0.0/numo/linalg
cd tmp/x86_64-darwin20/numo/linalg/blas/3.0.0
/Users/foo/.anyenv/envs/rbenv/versions/3.0.0/bin/ruby -I. ../../../../../../ext/numo/linalg/blas/extconf.rb
checking for numo/narray.h... yes
...
```
This changes do not affect the gem creation with the previous method:
```
$ bundle exec rake build
numo-linalg 0.1.5 built to pkg/numo-linalg-0.1.5.gem.
$ gem install pkg/numo-linalg-0.1.5.gem
Building native extensions. This could take a while...
Successfully installed numo-linalg-0.1.5
Parsing documentation for numo-linalg-0.1.5
Done installing …
```

Add rake-compiler to make build easier

---

.github/workflows/build.yml
lib/numo/linalg/autoloader.rb

I would like to add Ruby 3.0 and Head to CI like Numo::NArray. As a result of the added test, I found a variation in the notation of Linux OS in RbConfig::CONFIG['host_os'], so I fixed the library directory searched by autoloader.

Add 3.0 and Head to the version of Ruby running in CI

---

lib/numo/linalg/autoloader.rb

This change tweaks the autoloader for Windows, especially for Ruby Installer 2.
Ruby Installer 2 adds the bin directory of its MSYS2 (a.k.a. DEVKIT) in the default DLL search directories.  This directory is the location of the DLLs installed by pacman command.
If we try libraries only with their names like `Fiddle.dlopen("libopenblas.dll")` first, the autoloader makes it easier to use libraries installed by pacman command.

Tweak autoloader for Windows

---

ext/numo/linalg/blas/extconf.rb
ext/numo/linalg/lapack/extconf.rb

Installation of Numo::Linalg fails with Xcode14 and Ruby 3.1 as follows:
```sh
$ xcodebuild -version
Xcode 14.1
Build version 14B47b
$ ruby -v
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [arm64-darwin21]
$ gem install numo-linalg
Fetching numo-linalg-0.1.7.gem
Building native extensions. This could take a while...
ERROR:  Error installing numo-linalg:
ERROR: Failed to build gem native extension.
...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [blas.bundle] Error 1
make failed, exit code 2
```
The cause is the same as the bug fixed in Ruby3.1.3.
https://www.ruby-lang.org/ja/news/2022/11/24/ruby-3-1-3-released/
https://bugs.ruby-lang.org/issues/18912
To fix this bug, add the `-undefined …

Add dynamic_lookup linker option for macOS and Ruby 3.1

---

lib/numo/linalg/autoloader.rb

My newer mac can not find paths like my old mac.
"cannot find MKL/OpenBLAS/ATLAS/BLAS-LAPACK library"
It appears new versions of Homebrew has new locations where it stores these files.
Could we please add these new search paths?

Add MacOS autoload paths for openblas/lapack for new homebrew
